### ISSUE TITLE
Remove the validator for Button type

### ISSUE THREAD

**Issue by loocao** [zzuu666/antue#46]
虽说antd只有`primary`,`dashed`,`danger`,`default`这几种type,但是它并没有限制自定义的类型,而且事实上这几种类型是满足不了实际需求的.
![image](https://user-images.githubusercontent.com/1457297/33749889-786ee7f6-dc0b-11e7-8ffb-ffab643f156f.png)
![image](https://user-images.githubusercontent.com/1457297/33749899-886b1f9e-dc0b-11e7-97d9-a8ece7ff5583.png)
![image](https://user-images.githubusercontent.com/1457297/33749915-952dada0-dc0b-11e7-9899-91d5ed7eac4f.png)

个人建议,除非在引起不稳定因素的必要情况下,其它情况尽量不要使用`oneOf`限定参数,这对扩展性并不是很友好.

**Comment by sky-admin** [comment]
嗯嗯，蛮好的建议， @zzuu666 怎么说？

**Comment by zzuu666** [comment]
antue只提供了四种，所以会用`oneOf`来检测类型。
而想要达到自定义类型，可以用指定类名来处理。
``` html
<atu-button class="my-custom-btn">Custom</atu-button>
```
``` css
.my-custom-btn {
  border: 1px solid red;
}
```
这种显示的自定义样式要强于，这种不易维护的写法。
``` html
<atu-button type="custom">Custom</atu-button>
```
``` css
.ant-btn-custom {
  border: 1px solid red;
}
```
